# Generated by Django 4.2.7 on 2023-12-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0015_rename_extra_data_new_usersocialauth_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSocialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dota2_id', models.CharField(blank=True, max_length=30, null=True)),
                ('social_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
        ),
    ]
