# Generated by Django 4.2.7 on 2023-12-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0015_rename_extra_data_new_usersocialauth_extra_data'),
        ('home', '0002_profile_delete_extrasocialdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamID3', models.CharField(max_length=30, unique=True)),
                ('user_social_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
