# Generated by Django 4.2.7 on 2023-12-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_steamuser_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='steamID3',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
