# Generated by Django 4.2.7 on 2023-12-17 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0015_rename_extra_data_new_usersocialauth_extra_data'),
        ('home', '0005_remove_steamuser_id_alter_steamuser_steamid3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='user_social_auth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth'),
        ),
    ]
