# Generated by Django 4.2.7 on 2023-12-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_steamuser_steamid3'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='usefulness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_uid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='match_id',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='comment',
            name='steam_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.steamuser'),
        ),
    ]
