# Generated by Django 4.2.7 on 2023-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_comment_options_comment_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ratings',
            field=models.JSONField(default={'smurf': 0}),
        ),
    ]
