# Generated by Django 4.2.7 on 2023-12-17 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_steamuser_id_alter_steamuser_steamid3'),
        ('player', '0003_comment_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='steam_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.steamuser'),
        ),
    ]
