# Generated by Django 4.2.7 on 2023-12-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_comment_steam_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='match_id',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
