# Generated by Django 4.2.7 on 2023-12-23 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_alter_comment_match_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
