# Generated by Django 4.2.7 on 2023-12-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_uid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='match_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
